# Generated by Django 5.2.8 on 2025-11-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tiket", models.CharField(max_length=10, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACAO", "Ação"),
                            ("FLLS", "Fundos imobiliários"),
                            ("COMMODITIES", "Commodities"),
                            ("RENDA_FIXA", "Renda Fixa"),
                        ],
                        default="ACAO",
                        max_length=255,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
    ]
