# Generated by Django 5.2.8 on 2025-11-28 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("investing", "__first__"),
        ("portifolio", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantidade_ativos", models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ("preco_medio", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "name_tikets",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nome_ativo",
                        to="investing.assets",
                    ),
                ),
                (
                    "portifolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holding",
                        to="portifolio.portifolio",
                    ),
                ),
            ],
            options={
                "unique_together": {("portifolio", "name_tikets")},
            },
        ),
    ]
